### PR TITLE
Notifications have been implemented

### PR DESCRIPTION
**Pull request by MarcusSamuelsson**

### CODE REVIEW

**Review by pontuspr — APPROVED** [review]
Looks good to me. Is the getStatus method that is commented out going to be used for anything?

**Review by YavizGuldalf — CHANGES_REQUESTED** [review]
cloneTest should not be pushed to the repo

**Comment by YavizGuldalf** [comment]
Maybe add the line 
` **/cloneTest/** `
to the gitignore?

**Comment by MarcusSamuelsson** [comment]
> Looks good to me. Is the getStatus method that is commented out going to be used for anything?

Thought I might use it for testing but not so sure anymore

**Comment by MarcusSamuelsson** [comment]
> Maybe add the line `**/cloneTest/**` to the gitignore?

I'll fix that

**Review by YavizGuldalf — APPROVED** [review]
Looks good to me

**Pull request merged**
